---
- name: Add files to local repository
  shell: git add .
  args:
    chdir: /home/minduser/myplatform

- name: Commit changes
  shell: git commit -m "new release"
  args:
    chdir: /home/minduser/myplatform

- name: Push to repo
  shell: git push {{ origin }} master
  args:
    chdir: /home/minduser/myplatform
